import './globals.css';

export const metadata = {
  title: 'Cardapio de Restaurante',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={``}>{children}</body>
    </html>
  );
}
